### ISSUE TITLE
How to get your ROS package with solution architecture in your paper?

### ISSUE THREAD

**Issue by majiqiang** [yayaneath/GeoGrasp#5]
Hi, Brayan, I'm very interested to your project about Geograsp, and I read your that paper completely. Could you provide your complete solution architecture to me? I want to know how to define some ROS nodes such as “pointcloud_listener” you mentioned. Thank you very much!

**Comment by yayaneath** [comment]
Hi @majiqiang 

Thanks for showing interest on our project. Unfortunately, I cannot provide you with the exact copy of our architecture since there are confidential data regarding our laboratory (i.e. IPs, ports...). Basically, you can use the current [geograsp/src/cloud_processor.cpp](https://github.com/yayaneath/GeoGrasp/blob/master/geograsp/src/cloud_processor.cpp) as the _pointcloud_listener_ in the paper. Add to it a publisher node that publishes a custom message (_scene_objects_ in the paper) which holds the grasp configuration data.

Then, create some other node (_allegro_plan_grasp_ in the paper) that subscribes to that topic with the grasp configuration data and finds the way to translate our calculated grasp pose to your robotic system. This can simply be using the data in the object [GraspPose](https://github.com/yayaneath/GeoGrasp/blob/master/geograsp/include/geograsp/GeoGrasp.h#L38), transform it from the camera's reference frame to your robot or world, and then find a trajectory to move your robotic grasper to this pose (we used [MoveIt!](https://moveit.ros.org/) for that).
