### ISSUE TITLE
oppositeAxisVector variable and the setBackgroundPlaneCoeff function

### ISSUE THREAD

**Issue by tanjpg** [yayaneath/GeoGrasp#8]
Hi, May I know what is the purpose the oppositeAxisVector? The inline comments state that the   "Object's axis is reversed for consistency". What does that mean?

Also, for the setBackgroundPlaneCoeff  function, where is it called? I cant seem to find it in the cloud_processing.cpp script or the GeoGrasp.cpp script. 

Thanks for your help!

**Comment by yayaneath** [comment]
Hi,

**oppositeAxisVector**

The object's axis is approximated using PCA. The direction of such vector is not of relevance for the purpose of PCA. As a consequence, for the very same cloud, PCA might return a vector pointing in a positive or negative direction, though it would still represent the same main component of the points distribution.

In contrast, this direction determines the location of the 1st and 2nd grasping points. That is: if we reverse a vector, the 1st and 2nd grasping point exchange their values. For a parallel gripper this is not relevant since such grasper does not have a 1st or 2nd finger. However, for multifingered hands, swapping the 1st and 2nd grasping points means that the thumb swaps its target location. This could result in a grasp pose that might not be reachable due to the robot's orientation.

Due to this effect of the direction of the object's axis (PCA), we decided to keep the orientation consistent so that vectors pointed forward from the camera's origin. In case you are using a parallel gripper, this will not change anything for you. However, if you use a multifingered hand, this can ease the task of orienting your robot.

**setBackgroundPlaneCoeff**

This was an auxiliary function used for internal experiments. You can ignore that one. Sorry for the inconvenience.
