### ISSUE TITLE
How to use this to generate point cloud objects in Gazebo classic or ignition gazebo?

### ISSUE THREAD

**Issue by addy1997** [yayaneath/GeoGrasp#9]

**Comment by yayaneath** [comment]
Hello,

GeoGrasp is not a package for generating point cloud objects. This package expects as input a point cloud that you need to generate, either using a camera stream, a PCL file or a ROS topic if you integrate GeoGrasp in ROS.

I close the issue since this question is related to Gazebo and not to GeoGrasp.

**Comment by addy1997** [comment]
@yayaneath, Thanks. By the way, can I extend it for ROS2?

**Comment by yayaneath** [comment]
Sure thing! If you'd like, fork this repo and update it to ROS2 so we can keep a reference to your work ;)
